# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 005b7b75fbe07ba32a7950b33a409ed4206556e3643fdc1b8651a1ff420bc6681ac2275c4ecd878938f6663f76907420af7dd47ab2e21deb366f87f877f66895

test:
  secret_key_base: 7d02befb0e1675301aa0538a6ea574a45ab1dea8de4b53f03f9748dcce0a7ec1b1d2201a54c45a12cabef4314a356003e1dc4329078e853f5ec057c99b052cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
